# Make file for Case Inverter, yeller, and checker
all: yeller caseInverter checker

caseInverter: AddressUtility.c caseInverter.c
yeller: AddressUtility.c yeller.c
checker: AddressUtility.c checker.c

clean:
	rm -f *.o *.err

